version: "3.8"

services:
  server:
    image: node:17.8.0-alpine3.15

    restart: always
    container_name: metar-db
    environment:
      - NODE_ENV=production
      - DB_CONNECTION=${DB_CONNECTION}
      - MONGO_DB_NAME=${MONGO_DB_NAME}

    working_dir: /metar-db/
    volumes:
      - ./:/metar-db:rw

    command: sh -c "yarn install && yarn start"

    labels:
      traefik.enable: true
      traefik.http.routers.metar-db.rule: "Host(`metar.lurb.org`)"
      traefik.http.routers.metar-db.entrypoints: websecure
      traefik.http.routers.metar-db.tls.certresolver: myresolver
      traefik.http.routers.metar-db.priority: 200
      traefik.http.services.metar-db.loadbalancer.server.port: 3031

networks:
  default:
    external:
      name: traefik
