services:
  server:
    image: node:18.4.0-alpine3.16

    restart: always
    environment:
      - NODE_ENV=production
      - DB_CONNECTION=mongodb://mongo:27017
      - MONGO_DB_NAME=metar

    working_dir: /metar-db/
    depends_on:
      - mongo
    volumes:
      - ./:/metar-db:rw

    command: sh -c "yarn install && yarn start"

    labels:
      traefik.enable: true
      traefik.http.routers.metar-db.rule: "Host(`metar.xccup.org`)"
      traefik.http.routers.metar-db.entrypoints: websecure
      traefik.http.routers.metar-db.tls.certresolver: myresolver
      traefik.http.routers.metar-db.priority: 200
      traefik.http.services.metar-db.loadbalancer.server.port: 3031

  mongo:
    image: mongo
    restart: always

networks:
  traefik:
    external: true
  internal:
    driver: bridge
