version: "3.8"

services:
  server:
    image: node:17.8.0-alpine3.15
    restart: always
    container_name: metar-db
    environment:
      - NODE_ENV=development
      - DB_CONNECTION=${DB_CONNECTION}
    working_dir: /metar-db/
    volumes:
      - ./:/metar-db:rw
    command: sh -c "yarn install && yarn dev"
    ports:
      - 3031:3031

 