version: "3.8"

services:
  server:
    build: .
    restart: always
    container_name: qnh-scraper-server
    environment:
      - NODE_ENV=production
      - DB_CONNECTION=${DB_CONNECTION}

    working_dir: /qnh-scraper/
    volumes:
      - ./:/qnh-scraper:rw

    command: ./docker-entrypoint.sh

    # ports:
    #   - 3031:3031

    # labels:
    #   traefik.enable: true
    #   traefik.http.routers.qnh-scraper.rule: "Host(qnh.lurb.org)"
    #   traefik.http.routers.qnh-scraper.entrypoints: websecure
    #   traefik.http.routers.qnh-scraper.tls.certresolver: myresolver
    #   traefik.http.routers.qnh-scraper.priority: 200
    #   traefik.http.services.qnh-scraper.loadbalancer.server.port: 3031

  