version: "3.8"

services:
  server:
    image: node:17.8.0-alpine3.15
    restart: always
    container_name: qnh-scraper-server
    environment:
      - NODE_ENV=development
      - DB_CONNECTION=${DB_CONNECTION}

    working_dir: /qnh-scraper/
    volumes:
      - ./:/qnh-scraper:rw

    command: ./docker-entrypoint.sh
    depends_on:
      - db
    ports:
      - 3031:3031

 