version: "3.8"

services:
  server:
    image: node:17.8.0-alpine3.15
    restart: always
    container_name: qnh-scraper
    environment:
      - NODE_ENV=development
      - DB_CONNECTION=${DB_CONNECTION}
      - MONGO_DB_NAME=${MONGO_DB_NAME}

    working_dir: /qnh-scraper/
    volumes:
      - ./:/qnh-scraper:rw

    command: ./docker-entrypoint.sh

 